# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
UserPokemon.destroy_all
Pokemon.destroy_all
Zone.destroy_all
ZonePokemon.destroy_all

#users

rick = User.create(name:"Rick", email: "rikmarqk@gmail.com", password: "1234", img_url: "guy.jpeg")
akram = User.create(name:"Paul Blart", email: "mallcop@gmail.com", password: "1234", img_url: "guy.jpeg")


#pokemon


# = Pokemon.create(name: "", kind: "", level: , dex_num: , move_one: "", move_two: "", move_three: "", move_four: "", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/.gif")

bulbasaur = Pokemon.create(name: "Bulbasaur", kind: "Grass/Poison", level: 15, dex_num: 1, move_one: "Razorleaf", move_two: "Vine Whip", move_three: "Poison Powder", move_four: "Sleep Powder", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/bulbasaur.gif", capt_num:75)
ivysaur = Pokemon.create(name: "Ivysaur", kind: "Grass/Poison", level: 16, dex_num: 2, move_one: "Synthesis", move_two: "Solar Beam", move_three: "Synthesis", move_four: "Leech Seed", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/ivysaur.gif", capt_num:75)
venusaur = Pokemon.create(name: "Venusaur", kind: "Grass/Poison", level: 86, dex_num: 3, move_one: "Razorleaf", move_two: "Vine Whip", move_three: "Slug Bomb", move_four: "Frenzy Plant", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/venusaur-f.gif", capt_num:75)
charmander = Pokemon.create(name: "Charmander", kind: "Fire", level: 15, dex_num: 4, move_one: "Ember", move_two: "Fire Spin", move_three: "Sunny Day", move_four: "Tackle", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/charmander.gif", capt_num:75)
charmeleon = Pokemon.create(name: "Charmeleon", kind: "Fire", level: 32, dex_num: 5, move_one: "Iron Claw", move_two: "Fire Spin", move_three: "Bite", move_four: "Ember", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/charmeleon.gif", capt_num:75)
charizard = Pokemon.create(name: "Charizard", kind: "Fire/Flying", level: 100, dex_num: 6, move_one: "Fire Blast", move_two: "Fire Spin", move_three: "Blast Burn", move_four: "Flamethrower", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/charizard.gif", capt_num:75)
squirtle = Pokemon.create(name: "Squirtle", kind: "Water", level: 10, dex_num: 7, move_one: "Water Gun", move_two: "Bubble", move_three: "Protect", move_four: "Rapid Spin", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/squirtle.gif", capt_num:75)
wartortle = Pokemon.create(name: "Wartortle", kind: "Water", level: 35, dex_num: 8, move_one: "Skull Bash", move_two: "Rain Dance", move_three: "Hydro Pump", move_four: "Waterfall", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/wartortle.gif", capt_num:75)
blastoise = Pokemon.create(name: "Blastoise", kind: "Water", level: 100, dex_num: 9, move_one: "Water Cannon", move_two: "Hydro Pump", move_three: "Water Gun", move_four: "Surf", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/blastoise.gif", capt_num:75)
caterpie = Pokemon.create(name: "Caterpie", kind: "Bug", level: 5, dex_num: 10, move_one: "Tackle", move_two: "String Shot", move_three: "Bug Bite", move_four: "(none)", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/caterpie.gif", capt_num:75)
metapod = Pokemon.create(name: "Metapod", kind: "Bug", level: 9, dex_num: 11, move_one: "Harden", move_two: "String Shot", move_three: "(none)", move_four: "(none)", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/metapod.gif", capt_num:75)
butterfree = Pokemon.create(name: "Butterfree", kind: "Bug/Flying", level: 44, dex_num: 12, move_one: "Air Slash", move_two: "Rage Powder", move_three: "Bug Buzz", move_four: "Supersonic", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/butterfree.gif", capt_num:75)
weedle = Pokemon.create(name: "Weedle", kind: "Bug/Poison", level: 6, dex_num: 13, move_one: "Poison Sting", move_two: "Poison Shot", move_three: "(none)", move_four: "(none)", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/weedle.gif", capt_num:75)
kakuna = Pokemon.create(name: "Kakuna", kind: "Bug/Poison", level: 9, dex_num: 14, move_one: "Harden", move_two: "(none)", move_three: "(none)", move_four: "(none)", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/kakuna.gif", capt_num:75)
beedrill = Pokemon.create(name: "Beedrill", kind: "Bug/Poison", level: 45, dex_num: 15, move_one: "Fell Stinger", move_two: "Venoshot", move_three: "Toxic Spikes", move_four: "Rage", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/beedrill.gif", capt_num:75)
pidgey= Pokemon.create(name: "Pidgey", kind: "Normal/Flying", level: 17, dex_num: 16, move_one: "Twister", move_two: "Wing Attack", move_three: "Tackle", move_four: "Quick Attack", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/pidgey.gif", capt_num:75)
pidgeotto = Pokemon.create(name: "Pidgeotto", kind: "Normal/Flying", level: 35, dex_num: 17, move_one: "Hurricane", move_two: "Whirlwind", move_three: "Roost", move_four: "Aerial Ace", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/pidgeotto.gif", capt_num:75)
pidgeot = Pokemon.create(name: "Pidgeot", kind: "Normal/Flying", level: 67, dex_num: 18, move_one: "Aerial Ace", move_two: "Air Slash", move_three: "Hurricane", move_four: "Wing Attack", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/pidgeot.gif", capt_num:75)
rattata= Pokemon.create(name: "Rattata", kind: "Normal", level: 19, dex_num: 19, move_one: "Quick Attack", move_two: "Focus Energy", move_three: "Tackle", move_four: "Bite", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/rattata.gif", capt_num:75)
raticate = Pokemon.create(name: "Raticate", kind: "Normal", level: 50, dex_num: 20, move_one: "Sucker Punch", move_two: "Assurance", move_three: "Crunch", move_four: "Hyper Fang", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/raticate.gif", capt_num:75)
spearow = Pokemon.create(name: "Spearow", kind: "Normal/Flying", level: 19, dex_num: 21, move_one: "Peck", move_two: "Growl", move_three: "Leer", move_four: "Pursuit", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/spearow.gif", capt_num:75)
fearow = Pokemon.create(name: "Fearow", kind: "Normal/Flying", level: 55, dex_num: 22, move_one: "Drill Run", move_two: "Roost", move_three: "Aerial Ace", move_four: "Drill Peck", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/fearow.gif", capt_num:75)
ekans = Pokemon.create(name: "Ekans", kind: "Poison", level: 21, dex_num: 23, move_one: "Poison Sting", move_two: "Bite", move_three: "Glare", move_four: "Acid", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/ekans.gif", capt_num:75)
arbok = Pokemon.create(name: "Arbok", kind: "Poison", level: 66, dex_num: 24, move_one: "Gastro Acid", move_two: "Belch", move_three: "Acid Spray", move_four: "Coil", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/arbok.gif", capt_num:75)
pikachu = Pokemon.create(name: "Pikachu", kind: "Electric", level: 75, dex_num: 25, move_one: "Shock", move_two: "Shock Wave", move_three: "Quick Attack", move_four: "Thunderbolt", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/pikachu-f.gif", capt_num:75)
raichu= Pokemon.create(name: "Raichu", kind: "Electric", level: 65, dex_num: 26, move_one: "Thunder", move_two: "Volt Switch", move_three: "Wild Charge", move_four: "Charge Beam", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/raichu.gif", capt_num:75)
sandshrew = Pokemon.create(name: "Sandshrew", kind: "Ground", level: 21, dex_num: 27, move_one: "Swift", move_two: "Dig", move_three: "Swords Dance", move_four: "Rollout", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/sandshrew.gif", capt_num:75)
sandslash= Pokemon.create(name: "Slandslash", kind: "Ground", level: 44, dex_num: 28, move_one: "Earthquake", move_two: "Slash", move_three: "Sandstorm", move_four: "Sand Tomb", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/sandslash.gif", capt_num:75)
nidoranf= Pokemon.create(name: "Nidoran ♀", kind: "Poison", level: 15, dex_num: 29, move_one: "Growl", move_two: "Tail Whip", move_three: "Poison Sting", move_four: "Bite", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/nidoran-f.gif", capt_num:75)
nidorina= Pokemon.create(name: "Nidorina", kind: "Poison", level: 33, dex_num: 30, move_one: "Toxic Spikes", move_two: "Fury Swipes", move_three: "Double Kick", move_four: "Helping Hand", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/nidorina.gif", capt_num:75)
nidoqueen= Pokemon.create(name: "Nidoqueen", kind: "Poison/Ground", level: 71, dex_num: 31, move_one: "Poison Fang", move_two: "Flatter", move_three: "Crunch", move_four: "Captivate", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/nidoqueen.gif", capt_num:75)
nidoranm= Pokemon.create(name: "Nidoran ♂", kind: "Poison", level: 13, dex_num: 32, move_one: "Peck", move_two: "Focus Energy", move_three: "Double Kick", move_four: "Poison Sting", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/nidoran-m.gif", capt_num:75)
nidorino= Pokemon.create(name: "Nidorino", kind: "Poison", level: 32, dex_num: 33, move_one: "Leer", move_two: "Toxic Spikes", move_three: "Horn Attack", move_four: "Fury Attack", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/nidorino.gif", capt_num:75)
nidoking= Pokemon.create(name: "Nidoking", kind: "Poison/Ground", level: 76, dex_num: 34, move_one: "Megahorn", move_two: "Thrash", move_three: "Earth Power", move_four: "Chip Away", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/nidoking.gif", capt_num:75)
clefairy= Pokemon.create(name: "Clefairy", kind: "Normal", level: 33, dex_num: 35, move_one: "Bestow", move_two: "Double Slap", move_three: "Sing", move_four: "Encore", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/clefairy.gif", capt_num:75)
clefable= Pokemon.create(name: "Clefable", kind: "Normal", level: 66, dex_num: 36, move_one: "Spotlight", move_two: "Metronome", move_three: "Sing", move_four: "Minimize", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/clefable.gif", capt_num:75)
vulpix= Pokemon.create(name: "Vulpix", kind: "Fire", level: 37, dex_num: 37, move_one: "Ember", move_two: "Baby-Doll Eyes", move_three: "Fire Spin", move_four: "Quick Attack", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/vulpix.gif", capt_num:75)
ninetales = Pokemon.create(name:"Ninetales",kind: "Fire",level: 55,dex_num: 38,move_one: "Flamethrower", move_two: "Quick Attact", move_three: "Imprison", move_four: "Confuse Ray", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/ninetales.gif", capt_num:75)
jigglypuff= Pokemon.create(name: "Jigglypuff", kind: "Normal", level: 22, dex_num: 39, move_one: "Sing", move_two: "Disable", move_three: "Play Nice", move_four: "Pound", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/jigglypuff.gif", capt_num:75)
wigglytuff= Pokemon.create(name: "Wigglytuff", kind: "Normal", level: 44, dex_num: 40, move_one: "Disable", move_two: "Defense Curl", move_three: "Play Rough", move_four: "Double-Edge", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/wigglytuff.gif", capt_num:75)
zubat= Pokemon.create(name: "Zubat", kind: "Poison/Flying", level: 21, dex_num: 41, move_one: "Absorb", move_two: "Swift", move_three: "Astonish", move_four: "Swift", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/zubat.gif", capt_num:75)
golbat= Pokemon.create(name: "Golbat", kind: "Poison/Flying", level: 37, dex_num: 42, move_one: "Air Slash", move_two: "Haze", move_three: "Leech Life", move_four: "Venoshock", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/golbat.gif", capt_num:75)
oddish= Pokemon.create(name: "Oddish", kind: "Grass/Poison", level: 19, dex_num: 43, move_one: "Absorb", move_two: "Sleep Powder", move_three: "Stun Spore", move_four: "Sweet ", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/oddish.gif", capt_num:75)
gloom= Pokemon.create(name: "Gloom", kind: "Grass/Poison", level: 55, dex_num: 44, move_one: "Mega Drain", move_two: "Moonlight", move_three: "Sleep Powder", move_four: "Giga Drain", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/gloom.gif", capt_num:75)
vileplume= Pokemon.create(name: "Vileplume", kind: "Grass/Poison", level: 79, dex_num: 45, move_one: "Solar Beam", move_two: "Petal Blizzard", move_three: "Aromatherapy", move_four: "Petal Dance", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/vileplume.gif", capt_num:75)
paras= Pokemon.create(name: "Paras", kind: "Bug/Grass", level: 21, dex_num: 46, move_one: "Slash", move_two: "Growth", move_three: "Scratch", move_four: "Poison Powder", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/paras.gif", capt_num:75)
parasect= Pokemon.create(name: "Parasect", kind: "Bug/Grass", level: 43, dex_num: 47, move_one: "X-Scissor", move_two: "Rage Powder", move_three: "Giga Drain", move_four: "Rage Powder", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/parasect.gif", capt_num:75)
venonat= Pokemon.create(name: "Venonat", kind: "Bug/Poison", level: 30, dex_num: 48, move_one: "Sleep Powder", move_two: "Confusion", move_three: "Disable", move_four: "Tackle", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/venonat.gif", capt_num:75)
venomoth= Pokemon.create(name: "Venomoth", kind: "Bug/Poison", level: 62, dex_num: 49, move_one: "Quiver Dance", move_two: "Psychic", move_three: "Bug Buzz", move_four: "Zen Headbutt", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/venomoth.gif", capt_num:75)
diglett= Pokemon.create(name: "Diglett", kind: "Ground", level: 25, dex_num: 50, move_one: "Sand Attack", move_two: "Mud-Slap", move_three: "Magnitude", move_four: "Growl", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/diglett.gif", capt_num:75)
dugtrio= Pokemon.create(name: "Dugtrio", kind: "Ground", level: 37, dex_num: 51, move_one: "Bulldoze", move_two: "Fissure", move_three: "Earthquake", move_four: "Earth Power", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/dugtrio.gif", capt_num:75)
meowth= Pokemon.create(name: "Meowth", kind: "Normal", level: 27, dex_num: 52, move_one: "Scratch", move_two: "Fang Out", move_three: "Bite", move_four: "Screech", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/meowth.gif", capt_num:75)
persian= Pokemon.create(name: "Persia", kind: "Normal", level: 65, dex_num: 53, move_one: "Feint", move_two: "Night Slash", move_three: "Nasty Plot", move_four: "Assurance", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/persian.gif", capt_num:75)
psyduck= Pokemon.create(name: "Psyduck", kind: "Water", level: 32, dex_num: 54, move_one: "Tail Whip", move_two: "Water Gun", move_three: "Confusion", move_four: "Water Pulse", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/psyduck.gif", capt_num:75)
golduck= Pokemon.create(name: "Golduck", kind: "Water", level: 52, dex_num: 55, move_one: "Hydro Pump", move_two: "Amnesia", move_three: "Soak", move_four: "Zen Headbutt", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/golduck.gif", capt_num:75)
mankey= Pokemon.create(name: "Mankey", kind: "Fighting", level: 27, dex_num: 56, move_one: "Covet", move_two: "Focus Energy", move_three: "Karate Chop", move_four: "Low Kick", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/mankey.gif", capt_num:75)
primeape= Pokemon.create(name: "Primeape", kind: "Fighting", level: 37, dex_num: 57, move_one: "Final Gambit", move_two: "Stomping Tantrum", move_three: "Close Combat", move_four: "Outrage", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/primeape.gif", capt_num:75)
growlithe= Pokemon.create(name: "Growlithe", kind: "Fire", level: 36, dex_num: 58, move_one: "Roar", move_two: "Ember", move_three: "Helping Hand", move_four: "Odor Sleuth", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/growlithe.gif", capt_num:75)
arcan = Pokemon.create(name: "Arcanine",kind: "Fire",level: 65,dex_num: 59,move_one: "Fire Fang", move_two: "Extreme Speed", move_three: "Thunder Fang", move_four: "Roar", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/arcanine.gif", capt_num:75)
poliwag= Pokemon.create(name: "Poliwag", kind: "Water", level: 24, dex_num: 60, move_one: "Water Sport", move_two: "Bubble", move_three: "Rain Dance", move_four: "Water Gun", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/poliwag.gif", capt_num:75)
poliwhirl= Pokemon.create(name: "Poliwhirl", kind: "Water", level: 44, dex_num: 61, move_one: "Bubble Beam", move_two: "Mud Shot", move_three: "Wake-Up Slap", move_four: "Belly Drum", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/poliwhirl.gif", capt_num:75)
poliwrath= Pokemon.create(name: "Poliwrath", kind: "Water/Fighting", level: 81, dex_num: 62, move_one: "Circle Throw", move_two: "Dynamic Punch", move_three: "Bubble Beam", move_four: "Submission", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/poliwrath.gif", capt_num:75)
abra= Pokemon.create(name: "Abra", kind: "Psychic", level: 15, dex_num: 63, move_one: "Teleport", move_two: "(none)", move_three: "(none)", move_four: "(none)", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/abra.gif", capt_num:75)
kadabra= Pokemon.create(name: "Kadabra", kind: "Psychic", level: 65, dex_num: 64, move_one: "Psybeam", move_two: "Miracle Eye", move_three: "Kinesis", move_four: "Reflect", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/kadabra.gif", capt_num:75)
alakazam = Pokemon.create(name: "Alakazam",kind: "Psychic",level: 86,dex_num: 65,move_one: "Psychic", move_two: "Psycho-Cut", move_three: "Ally Switch", move_four: "Teleport", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/alakazam.gif", capt_num:75)
machop = Pokemon.create(name: "Machop", kind: "Fighting", level: 26, dex_num: 66, move_one: "Low Kick", move_two: "Karate Chop", move_three: "Low Sweep", move_four: "Foresight", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/machop.gif", capt_num:75)
machoke = Pokemon.create(name: "Machoke", kind: "Fighting", level: 58, dex_num: 67, move_one: "Seismic Toss", move_two: "Revenge", move_three: "Vital Throw", move_four: "Knock Off", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/machoke.gif", capt_num:75)
machamp= Pokemon.create(name: "Machamp", kind: "Fighting", level: 99, dex_num: 68, move_one: "Dynamic Punch", move_two: "Bulk Up", move_three: "Dual Chop", move_four: "Cross Chop", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/machamp.gif", capt_num:75)
bellsprout= Pokemon.create(name: "Bellsprout", kind: "Grass/Poison", level: 20, dex_num: 69, move_one: "Vine Whip", move_two: "Wrap", move_three: "Growth", move_four: "Stun Spore", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/bellsprout.gif", capt_num:75)
weepinbell = Pokemon.create(name: "Weepinbell", kind: "Grass/Poison", level: 41, dex_num: 70, move_one: "Sweet Scent", move_two: "Acid", move_three: "Razor Leaf", move_four: "Slam", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/weepinbell.gif", capt_num:75)
victree = Pokemon.create(name: "Victreebel",kind: "Grass/Poison",level: 84,dex_num: 71,move_one: "Leaf Blade", move_two: "Swallow", move_three: "Spit-up", move_four: "Leaf Tornado", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/victreebel.gif", capt_num:75)
tentacool= Pokemon.create(name: "Tentacool", kind: "Water/Poison", level: 29, dex_num: 72, move_one: "Constrict", move_two: "Water Pulse", move_three: "Acid Spray", move_four: "Barrier", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/tentacool.gif", capt_num:75)
tentacruel= Pokemon.create(name: "Tentacruel", kind: "Water/Poison", level: 77, dex_num: 73, move_one: "Wring Out", move_two: "Hex", move_three: "Sludge Wave", move_four: "Hydro Pump", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/tentacruel.gif", capt_num:75)
greodude= Pokemon.create(name: "Geodude", kind: "Rock/Ground", level: 24, dex_num: 74, move_one: "Defense Curl", move_two: "Rock Polish", move_three: "Rock Throw", move_four: "Mud Sport", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/geodude.gif", capt_num:75)
graveler= Pokemon.create(name: "Graveler", kind: "Rock/Ground", level: 58, dex_num: 75, move_one: "Bulldoze", move_two: "Magnitude", move_three: "Self-Destruct", move_four: "Stealth Rock", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/graveler.gif", capt_num:75)
golem= Pokemon.create(name: "Golem", kind: "Rock/Ground", level: 83, dex_num: 76, move_one: "Stone Edge", move_two: "Heavy Slam", move_three: "Earthquake", move_four: "Double-Edge", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/golem.gif", capt_num:75)
ponyta= Pokemon.create(name: "Ponyta", kind: "Fire", level: 39, dex_num: 77, move_one: "Ember", move_two: "Fire Spin", move_three: "Stomp", move_four: "Growl", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/ponyta.gif", capt_num:75)
rapidash= Pokemon.create(name: "Rapidash", kind: "Fire", level: 79, dex_num: 78, move_one: "Flare Blitze", move_two: "Fire Blast", move_three: "Inferno", move_four: "Flame Charge", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/rapidash.gif", capt_num:75)
slowpoke= Pokemon.create(name: "Slowpoke", kind: "Water/Psychic", level: 36, dex_num: 79, move_one: "Curse", move_two: "Confusion", move_three: "Disable", move_four: "Headbutt", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/slowpoke.gif", capt_num:75)
slowbro= Pokemon.create(name: "Slowbro", kind: "Water/Psychic", level: 79, dex_num: 80, move_one: "Heal Pulse", move_two: "Psychic", move_three: "Rain Dance", move_four: "Water Pulse", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/slowbro.gif", capt_num:75)
magnemite= Pokemon.create(name: "Megnemite", kind: "Electric", level: 27, dex_num: 81, move_one: "Thunder Shock", move_two: "Magnet Bomb", move_three: "Sonic Boom", move_four: "Spark", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/magnemite.gif", capt_num:75)
magneton= Pokemon.create(name: "Magneton", kind: "Electric", level: 69, dex_num: 82, move_one: "Electro Ball", move_two: "Lock-On", move_three: "Zap Cannon", move_four: "Magnet Rise", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/magneton.gif", capt_num:75)
farfetchd= Pokemon.create(name: "Farfetch'd", kind: "Normal/Flying", level: 45, dex_num: 83, move_one: "Brave Bird", move_two: "Air Slash", move_three: "Feint", move_four: "Air Cutter", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/farfetchd.gif", capt_num:75)
doduo= Pokemon.create(name: "Doduo", kind: "Normal/Flying", level: 30, dex_num: 84, move_one: "Pluck", move_two: "Uproar", move_three: "Acupressure", move_four: "Pursuit", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/doduo.gif", capt_num:75)
dodrio= Pokemon.create(name: "Dodrio", kind: "Normal/Flying", level: 67, dex_num: 85, move_one: "Thrash", move_two: "Endeavor", move_three: "Jump Kick", move_four: "Agility", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/dodrio.gif", capt_num:75)
seel= Pokemon.create(name: "Seel", kind: "Water", level: 31, dex_num: 86, move_one: "Rest", move_two: "Ice Shard", move_three: "Headbutt", move_four: "Aqua Ring", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/seel.gif", capt_num:75)
dewgong= Pokemon.create(name: "Dewgong", kind: "Water/Ice", level: 88, dex_num: 87, move_one: "Hail", move_two: "Ice Beam", move_three: "Dive", move_four: "Brine", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/dewgong.gif", capt_num:75)
grimer= Pokemon.create(name: "Grimer", kind: "Poison", level: 32, dex_num: 88, move_one: "Harden", move_two: "Poison Gas", move_three: "Sludge", move_four: "Mud-Slap", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/grimer.gif", capt_num:75)
muk = Pokemon.create(name: "Muk", kind: "Poison", level: 85, dex_num: 89, move_one: "Gunk Shot", move_two: "Poison Jab", move_three: "Infestation", move_four: "Lick", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/muk.gif", capt_num:75)
shellder= Pokemon.create(name: "Shellder", kind: "Water", level: 44, dex_num: 90, move_one: "Withdraw", move_two: "Protect", move_three: "Clamp", move_four: "Icicle Spear", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/shellder.gif", capt_num:75)
cloy = Pokemon.create(name: "Cloyster",kind: "Water/Ice",level: 96,dex_num: 91,move_one: "Icicle Crash", move_two: "Aurora Beam", move_three: "Supersonic", move_four: "Toxic Spikes", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/cloyster.gif", capt_num:75)
gastly= Pokemon.create(name: "Gastly", kind: "Ghost/Poison", level: 22, dex_num: 92, move_one: "Lick", move_two: "Hypnosis", move_three: "Night Shade", move_four: "Sucker Punch", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/gastly.gif", capt_num:75)
haunter= Pokemon.create(name: "Haunter", kind: "Ghost/Poison", level: 66, dex_num: 93, move_one: "Shadow Ball", move_two: "Payback", move_three: "Dark Pulse", move_four: "Destiny Bond", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/haunter.gif", capt_num:75)
gengar = Pokemon.create(name: "Gengar",kind: "Ghost/Poison",level: 100,dex_num: 94,move_one: "Nightmare", move_two: "Hypnosis", move_three: "Hex", move_four: "Dream Eater", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/gengar.gif", capt_num:75)
onix = Pokemon.create(name: "Onix",kind: "Rock/Ground",level: 98,dex_num: 95,move_one:"Rock Tomb", move_two: "Sand Tomb", move_three: "Iron Tail", move_four: "Sand Storm", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/onix.gif", capt_num:75)
drowzee= Pokemon.create(name: "Drowzee", kind: "Psychic", level: 22, dex_num: 96, move_one: "Hypnosis", move_two: "Meditate", move_three: "Headbutt", move_four: "Confusion", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/drowzee.gif", capt_num:75)
hypno= Pokemon.create(name: "Hypno", kind: "Psychic", level: 55, dex_num: 97, move_one: "Pyshock", move_two: "Synchronoise", move_three: "Swagger", move_four: "Future Sight", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/hypno.gif", capt_num:75)
krabby= Pokemon.create(name: "Krabby", kind: "Water", level: 21, dex_num: 98, move_one: "Vice Grip", move_two: "Bubble", move_three: "Bubble Beam", move_four: "Mud Sport", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/krabby.gif", capt_num:75)
kingler= Pokemon.create(name: "Kingler", kind: "Water", level: 49, dex_num: 99, move_one: "Crabhammer", move_two: "Guillotine", move_three: "Brine", move_four: "Metal Claw", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/kingler.gif", capt_num:75)
voltorb= Pokemon.create(name: "Voltorb", kind: "Electric", level: 27, dex_num: 100, move_one: "Charge", move_two: "Spark", move_three: "Screech", move_four: "Rollout", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/voltorb.gif", capt_num:75)
electrode = Pokemon.create(name: "Electrode", kind: "Electrode", level: 65, dex_num: 101, move_one: "Explosion", move_two: "Discharge", move_three: "Thunderbolt", move_four: "Thunder Shock", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/electrode.gif", capt_num:75)
exeggcute= Pokemon.create(name: "Exeggcute", kind: "Grass/Psychic", level: 22, dex_num: 102, move_one: "Bullet Seed", move_two: "Worry Seed", move_three: "Stun Spore", move_four: "Sleep Powder", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/exeggcute.gif", capt_num:75)
exeggutor = Pokemon.create(name: "Exeggutor",kind: "Grass/Psychic",level: 88,dex_num: 103,move_one: "Leaf Storm", move_two: "Hypnosis", move_three: "Confusion", move_four: "Egg-Bomb", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/exeggutor.gif", capt_num:75)
cubone= Pokemon.create(name: "Cubone", kind: "Ground", level: 27, dex_num: 104, move_one: "Bone Club", move_two: "Headbutt", move_three: "Bonemerang", move_four: "False Swipe", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/cubone.gif", capt_num:75)
marowak= Pokemon.create(name: "Marowak", kind: "Ground", level: 63, dex_num: 105, move_one: "Bone Rush", move_two: "Retaliate", move_three: "Endeavor", move_four: "Rage", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/marowak.gif", capt_num:75)
hitmonlee= Pokemon.create(name: "Hitmonlee", kind: "Fighting", level: 64, dex_num: 106, move_one: "Reversal", move_two: "Blaze Kick", move_three: "Close Combat", move_four: "Mega Kick", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonlee.gif", capt_num:75)
hitmonchan= Pokemon.create(name: "Hitmonchan", kind: "Fighting", level: 59, dex_num: 107, move_one: "Counter", move_two: "Focus Punch", move_three: "Sky Uppercut", move_four: "Fire Punch", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonchan.gif", capt_num:75)
lickitung= Pokemon.create(name: "Lickitung", kind: "Normal", level: 77, dex_num: 108, move_one: "Rollout", move_two: "Power Whip", move_three: "Slam", move_four: "Stomp", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/lickitung.gif", capt_num:75)
koffing= Pokemon.create(name: "Koffing", kind: "Poison", level: 33, dex_num: 109, move_one: "Clear Smog", move_two: "Haze", move_three: "Assurance", move_four: "Smokescreen", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/koffing.gif", capt_num:75)
weez = Pokemon.create(name:"Weezing",kind: "Poison",level: 66,dex_num: 110,move_one: "Smog", move_two: "Self Destruction", move_three: "Belch", move_four: "Poison Gas", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/weezing.gif", capt_num:75)
rhyhorn = Pokemon.create(name: "Rhyhorn", kind: "Ground/Rock", level: 40, dex_num: 111, move_one: "Rock Blast", move_two: "Horn Attack", move_three: "Scary Face", move_four: "Smack Down", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/rhyhorn.gif", capt_num:75)
rhydon = Pokemon.create(name: "Rhydon", kind: "Ground/Rock", level: 95, dex_num: 112, move_one: "Mud-Slug", move_two: "Earthquake", move_three: "Fissure", move_four: "Rock Blast", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/rhydon.gif", capt_num:75)
chansey= Pokemon.create(name: "Chansey", kind: "Normal", level: 53, dex_num: 113, move_one: "Refresh", move_two: "Soft-Boiled", move_three: "Healing Wish", move_four: "Fling", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/chansey.gif", capt_num:75)
tangela= Pokemon.create(name: "Tangela", kind: "Grass", level: 34, dex_num: 114, move_one: "Grassy Terrain", move_two: "Giga Drain", move_three: "Wring Out", move_four: "Power Whip", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/tangela.gif", capt_num:75)
kangaskhan= Pokemon.create(name: "Kangaskhan", kind: "Normal", level: 63, dex_num: 115, move_one: "Outrage", move_two: "Sucker Punch", move_three: "Reversal", move_four: "Dizzy Punch", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/kangaskhan.gif", capt_num:75)
horsea= Pokemon.create(name: "Horsea", kind: "Water", level: 31, dex_num: 116, move_one: "Bubble", move_two: "Twister", move_three: "Brine", move_four: "Leer", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/horsea.gif", capt_num:75)
seadra= Pokemon.create(name: "Seadra", kind: "Water", level: 68, dex_num: 117, move_one: "Dragon Dance", move_two: "Dragon Pulse", move_three: "Hydro Pump", move_four: "Bubble Beam", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/seadra.gif", capt_num:75)
goldeen= Pokemon.create(name: "Goldeen", kind: "Water", level: 32, dex_num: 118, move_one: "Peck", move_two: "Horn Attack", move_three: "Aqua Ring", move_four: "Supersonic", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/goldeen.gif", capt_num:75)
seaking= Pokemon.create(name: "Seaking", kind: "Water", level: 52, dex_num: 119, move_one: "Horn Drill", move_two: "Fury Attack", move_three: "Waterfall", move_four: "Megahorn", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/seaking.gif", capt_num:75)
staryu= Pokemon.create(name: "Staryu", kind: "Water", level: 45, dex_num: 120, move_one: "Rapid Spin", move_two: "Psywave", move_three: "Recover", move_four: "Swift", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/staryu.gif", capt_num:75)
starmie= Pokemon.create(name: "Starmie", kind: "Water/Psychic", level: 70, dex_num: 121, move_one: "Hydro Pump", move_two: "Rapid Spin", move_three: "Spotlight", move_four: "Confuse Ray", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/starmie.gif", capt_num:75)
mrmime= Pokemon.create(name: "Mr.Mime", kind: "Psychic", level: 64, dex_num: 122, move_one: "Baton Pass", move_two: "Psychic", move_three: "Role Play", move_four: "Safeguard", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/mr-mime.gif", capt_num:75)
scyther= Pokemon.create(name: "Scyther", kind: "Bug/Flying", level: 79, dex_num: 123, move_one: "Night Slash", move_two: "X-Scissor", move_three: "Razor Wind", move_four: "Fury Cutter", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/scyther.gif", capt_num:75)
jynx = Pokemon.create(name: "Jynx",kind: "Ice/Psychic",level: 67,dex_num: 124,move_one: "Blizzard", move_two: "Avalanche", move_three: "Double Slap", move_four: "Powder Snow", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/jynx.gif", capt_num:75)
electabuzz= Pokemon.create(name: "Electabuzz", kind: "Electric", level: 89, dex_num: 125, move_one: "Thunderbolt", move_two: "Thunder", move_three: "Thunder Punch", move_four: "Electro Ball", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/electabuzz.gif", capt_num:75)
magmar = Pokemon.create(name: "Magmar", kind: "Fire", level: 80, dex_num: 126, move_one: "Fire Blast", move_two: "Fire Punch", move_three: "Low Kick", move_four: "Sunny Day", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/magmar.gif", capt_num:75)
pinsir= Pokemon.create(name: "Pinsir", kind: "Bug", level: 76, dex_num: 127, move_one: "Guillotine", move_two: "Thrash", move_three: "X-Scissor", move_four: "Submission", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/pinsir.gif", capt_num:75)
tauros= Pokemon.create(name: "Tauros", kind: "Normal", level: 54, dex_num: 128, move_one: "Rest", move_two: "Zen Headbutt", move_three: "Thrash", move_four: "Double-Edge", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/tauros.gif", capt_num:75)
magikarp= Pokemon.create(name: "Magikarp", kind: "Water", level: 17, dex_num: 129, move_one: "Flail", move_two: "Splash", move_three: "Tackle", move_four: "(none)", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/magikarp.gif", capt_num:75)
gyarados = Pokemon.create(name: "Gyarados", kind: "Water/Flying", level: 100, dex_num: 130, move_one: "Hyper Beam", move_two: "Twister", move_three: "Hurricane", move_four: "Waterfall", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/gyarados.gif", capt_num:75)
lapras= Pokemon.create(name: "Lapras", kind: "Water/Ice", level: 85, dex_num: 131, move_one: "Sheer Cold", move_two: "Brine", move_three: "Hydro Pump", move_four: "Body Slam", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/lapras.gif", capt_num:75)
ditto= Pokemon.create(name: "Ditto", kind: "Normal", level: 94, dex_num: 132, move_one: "Transform", move_two: "(none)", move_three: "(none)", move_four: "(none)", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/ditto.gif", capt_num:75)
eevee = Pokemon.create(name: "Eevee", kind: "Normal", level: 44, dex_num: 133, move_one: "Tail Whip", move_two: "Double-Edge", move_three: "Copy Cat", move_four: "Take Down", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/eevee.gif", capt_num:75)
vaporeon= Pokemon.create(name: "Vaporeon", kind: "Water", level: 69, dex_num: 134, move_one: "Hydro Pump", move_two: "Last Resort", move_three: "Aurora Beam", move_four: "Acid Armor", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/vaporeon.gif", capt_num:75)
jolteon= Pokemon.create(name: "Jolteon", kind: "Electric", level: 88, dex_num: 135, move_one: "Thunder", move_two: "Thunder Fang", move_three: "Double-Kick", move_four: "Thunder Wave", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/jolteon.gif", capt_num:75)
flareon= Pokemon.create(name: "Flareon", kind: "Fire", level: 42, dex_num: 136, move_one: "Flare Blitze", move_two: "Fire Fang", move_three: "Fire Spin", move_four: "Smog", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/flareon.gif", capt_num:75)
porygon = Pokemon.create(name: "Porygon",kind: "Normal",level: 39,dex_num: 137,move_one: "Recover", move_two: "Lock-On", move_three: "Zap Cannon", move_four: "psybeam", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/porygon.gif", capt_num:75)
omanyte= Pokemon.create(name: "Omanyte", kind: "Rock/Water", level: 39, dex_num: 138, move_one: "Withdraw", move_two: "Rollout", move_three: "Mud Shot", move_four: "Brine", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/omanyte.gif", capt_num:75)
omastar= Pokemon.create(name: "Omastar", kind: "Rock/Water", level: 78, dex_num: 139, move_one: "Ancient Power", move_two: "Rock Blast", move_three: "Shell Smash", move_four: "Hydro Pump", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/omastar.gif", capt_num:75)
kabuto= Pokemon.create(name: "Kabuto", kind: "Rock/Water", level: 38, dex_num: 140, move_one: "Endure", move_two: "Absorb", move_three: "Scratch", move_four: "Sand Attack", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/kabuto.gif", capt_num:75)
kabutops= Pokemon.create(name: "Kabutops", kind: "Rock/Water", level: 97, dex_num: 141, move_one: "Night Slash", move_two: "Metal Sound", move_three: "Ancient Power", move_four: "Wring Out", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/kabutops.gif", capt_num:75)
aerodactyl = Pokemon.create(name: "Aerodactyl", kind: "Rock/Flying", level: 80, dex_num: 142, move_one: "Bite", move_two: "Supersonic", move_three: "Iron Head", move_four: "Giga Impact", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/aerodactyl.gif", capt_num:75)
snorlax= Pokemon.create(name: "Snorlax", kind: "Normal", level: 67, dex_num: 143, move_one: "High Horsepower", move_two: "Crunch", move_three: "Rest", move_four: "Belly Drum", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/snorlax.gif", capt_num:75)
articuno = Pokemon.create(name: "Articuno", kind: "Ice/Flying", level: 100, dex_num: 144, move_one: "Frost Breath", move_two: "Ice Beam", move_three: "Blizzard", move_four: "Ice Shard", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/articuno.gif", capt_num:75)
zapdos = Pokemon.create(name: "Zapdos", kind: "Electric/Flying", level: 100, dex_num: 145, move_one: "Thunder", move_two: "Electro Ball", move_three: "Zap Cannon", move_four: "Shock Wave", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/zapdos.gif", capt_num:75)
moltres = Pokemon.create(name: "Moltres", kind: "Fire/Flying", level: 100, dex_num: 146, move_one: "Burn Up", move_two: "Heat Wave", move_three: "Flamethrower", move_four: "Fire Spin", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/moltres.gif", capt_num:75)
dratini= Pokemon.create(name: "Dratini", kind: "Dragon", level: 26, dex_num: 147, move_one: "Wrap", move_two: "Dragon Rage", move_three: "Twister", move_four: "Slam", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/dratini.gif", capt_num:75)
dragonair= Pokemon.create(name: "Dragonair", kind: "Dragon", level: 54, dex_num: 148, move_one: "Dragon Dance", move_two: "Agility", move_three: "Safeguard", move_four: "Hyper Beam", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/dragonair.gif", capt_num:75)
dragonite = Pokemon.create(name: "Dragonite", kind: "Dragon/Flying", level: 95, dex_num: 149, move_one: "Dragon Tail", move_two: "Dragon Pulse", move_three: "Dragon Breath", move_four: "Dragon Claw", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/dragonite.gif", capt_num:75)
mewtwo = Pokemon.create(name: "Mewtwo", kind: "Psychic", level: 100, dex_num: 150, move_one: "Shadow Ball", move_two: "Psychic", move_three: "Recover", move_four: "Psystrike", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/mewtwo.gif", capt_num:75)
mew = Pokemon.create(name: "Mew", kind: "Psychic", level: 100, dex_num: 151, move_one: "Psychic", move_two: "Aura Sphere", move_three: "Amnesia", move_four: "Ancient Power", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/mew.gif", capt_num:75)


# = Pokemon.create(name: "", kind: "", level: , dex_num: , move_one: "", move_two: "", move_three: "", move_four: "", img_url: "https://img.pokemondb.net/sprites/black-white/anim/normal/.gif")

#zones
zone1 = Zone.create(name: "Volcan", description: "Firey Pits of Volcan, here, the floor REALLY is lava", img_url: "https://toppng.com/uploads/preview/volcano-art-lava-flash-11570448716wmkq11ovwl.jpg")
zone2 = Zone.create(name: "Seafoam", description: "Hope you know how to swim....or have a Pokemon that can", img_url: "https://images.nintendolife.com/ae5cb8011b972/armor.original.jpg")
zone3 = Zone.create(name: "Ice Age", description: "Bring a coat or three", img_url: "https://vignette3.wikia.nocookie.net/legendarymob/images/c/ca/Ice_cave.jpg/revision/latest?cb=20160924215941")
zone4 = Zone.create(name: "Voltage", description: "You'll be shocked to see what's here", img_url: "https://pm1.narvii.com/5813/6f41acc29155c9641b897841189ff3206f2475d2_hq.jpg")
zone5 = Zone.create(name: "Grassy Plains", description: "Grean, leafy and wide open spaces", img_url: "https://cdn.bulbagarden.net/upload/thumb/8/8c/Sky-Blue_Plains_RTDX.png/1200px-Sky-Blue_Plains_RTDX.png")
zone6 = Zone.create(name: "Legendary Island", description: "Bring a lot of Full Restore", img_url: "https://cdn.bulbagarden.net/upload/thumb/7/7c/Legendary_Island_RTDX.png/1200px-Legendary_Island_RTDX.png")
zone7 = Zone.create(name: "Chernobyl", description: "Hazardous AF", img_url: "https://pokemongamersblog.files.wordpress.com/2008/09/torn_world.png")

#ZONE POKEMON
#fire_zone

ZonePokemon.create(zone_id:zone1.id, pokemon_id: charizard.id)
ZonePokemon.create(zone_id:zone1.id, pokemon_id: rhydon.id)
ZonePokemon.create(zone_id:zone1.id, pokemon_id: magmar.id)
ZonePokemon.create(zone_id:zone1.id, pokemon_id: aerodactyl.id)

# #water_zone
ZonePokemon.create(zone_id: zone2.id, pokemon_id: blastoise.id)
ZonePokemon.create(zone_id: zone2.id, pokemon_id: gyarados.id)

# #ice_zone
ZonePokemon.create(zone_id:zone3.id, pokemon_id:jynx.id)
ZonePokemon.create(zone_id:zone3.id, pokemon_id:cloy.id)

# #electric_zone
ZonePokemon.create(zone_id:zone4.id, pokemon_id:porygon.id)
ZonePokemon.create(zone_id:zone4.id, pokemon_id:muk.id)
ZonePokemon.create(zone_id:zone4.id, pokemon_id:electrode.id)

# #grass/normal_zone
ZonePokemon.create(zone_id:zone5.id, pokemon_id:dragonite.id)
ZonePokemon.create(zone_id:zone5.id, pokemon_id:exeggutor.id)
ZonePokemon.create(zone_id:zone5.id, pokemon_id:victree.id)
ZonePokemon.create(zone_id:zone5.id, pokemon_id:bulbasaur.id)

# #legendary_zone
ZonePokemon.create(zone_id:zone6.id, pokemon_id:mew.id)
ZonePokemon.create(zone_id:zone6.id, pokemon_id:mewtwo.id)
ZonePokemon.create(zone_id:zone6.id, pokemon_id:articuno.id)
ZonePokemon.create(zone_id:zone6.id, pokemon_id:zapdos.id)
ZonePokemon.create(zone_id:zone6.id, pokemon_id:moltres.id)

# #poison_zone
ZonePokemon.create(zone_id:zone7.id, pokemon_id:muk.id)
ZonePokemon.create(zone_id:zone7.id, pokemon_id:gengar.id)
ZonePokemon.create(zone_id:zone7.id, pokemon_id:weez.id)

# #user_pokemons
UserPokemon.create(nickname: "Torchy", user_id: rick.id, pokemon_id: charizard.id)
UserPokemon.create(nickname: "Rocky", user_id: rick.id, pokemon_id: rhydon.id)
UserPokemon.create(nickname: "MewMew", user_id: akram.id, pokemon_id: mewtwo.id)
UserPokemon.create(nickname: "Blasty", user_id: akram.id, pokemon_id: blastoise.id)